### ISSUE TITLE
How to obtain imputed genome in vcf format with GBScleanR?

### ISSUE THREAD

**Issue by Lanique2** [tomoyukif/GBScleanR#3]
Dear Furuta, T., Yamamoto, T., Ashikari, M,

I would like to use GBScleanR for genome imputation, but ran into a problem when I tried to obtain the output. The sample data included in the package can be used as example. If the gds data is created, loaded, parents are defined and loaded with setParents(), and then the information is written to out_fn as described in the vignette, with gbsrGDS2VCF(gds, out_fn), everything works perfectly. However, when the function estGeno(gds, het_parent=TRUE, iter=4) and following functions to obtain the imputed genome are included, the following error message is shown when the function gbsrGDS2VCF(gds, out_fn) is run:

Error in openfn.gds(gds.fn, readonly = readonly, allow.fork = TRUE, allow.duplicate = allow.duplicate) : 
  Stream Read Error, need 12 byte(s) but receive 0

The function gbsrGDS2CSV(gds, out_fn2, node = "cor") works fine, so the contents of the gds object seem fine. However, it would be great if an output in vcf format could be obtained.

I hope you can help us with that.
Kind regards

**Comment by tomoyukif** [comment]
Thank you so much for trying GBScleanR!
The error message that you got was usually shown after a process accessing the GDS file was interrupted accidentally.
Node manipulation also cause the same error, but I don't know the reason.
Since GBScleanR uses the gdsfmt package to access a GDS file, I cannot fix this kind of error.
Only one solution I know is to make a GDS file from a VCF file again.
I tested the latest version of GBScleanR yesterday and could process data with gbsrVCF2GDS(), estGeno(), and gbsrGDS2VCF().
If you got the same error again, please tell me and send me your data if you can.

By the way, I added an argument `node` in gbsrGDS2VCF(). 
The previous version of gbsrGDS2VCF() was the function to generate a VCF file in which the genotype in the GT field was obtained from the genotype node of the given GDS file and the estimated (corrected) genotype data was stored in the CGT field.
I noticed that some software only recognize the genotype data in the GT field as genotype data and the data in the CGT field would be ignored.
Therefore, the latest version of GBScleanR has the `node` argument in gbsrGDS2VCF() and the setting `node = "cor"` makes the function output the estimated genotype data into the GT field.
The latest version is available on GitHub.
Bioconductor version is not the latest version due to its release cycle.
